### ISSUE TITLE
CSP breaks when new line characters are in the fields

### ISSUE THREAD

**Issue by zshahan** [16patsle/wordpress-csp-manager#2]
When a new line character is added to one of the fields, like script-src, a php error is thrown and the content-security-policy header does not get set.

FastCGI sent in stderr: "PHP message: PHP Warning:  Header may not contain more than a single header, new line detected in /home/www/www/wordpress-web/wp-content/plugins/csp-manager/src/CSP_Manager/Core.php on line 72" while reading response header from upstream, client: 192.168.1.216, server: www.example.com, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.example.com"

It would be great if the plugin sanitized the field when saving and removed the new line character or replaced it with a space.

**Comment by zshahan** [comment]
I'd prefer to remove any newlines when saved.  I'm not sure if maybe some UX changes would help?  When adding to some of the fields, if there are a lot of urls, they trail off into the input box.  Maybe some form of array input (click button to add another element) might work?

Either way, thanks for making this plug-in, it makes it way easier to handle the csp header rather than in nginx config or something similar.

**Comment by 16patsle** [comment]
I believe I intended to close this with #5 back in October. Let me know if there still are issues
